### ISSUE TITLE
More than one of the same Block causes data confusion

### ISSUE THREAD

**Issue by signaturesteve** [rchipka/advanced-custom-blocks#21] opened 2018-10-09 16:07 UTC
So I created a block, it has a couple of text inputs and some post object fields.   If I have one of these on a page... fine.   As soon as I add a second it seems to be pre-populated with the data from the previous block and gets confused when I try and edit it.   Basically unusable.

**Comment by rchipka** [comment] 2018-10-09 16:14
Duplicate of #3 

Also, when reporting bugs to GitHub, avoid adding comments like "Basically unusable".

This is, after all, open source software developed by people willing to donate their spare time and then share it for free (months before the paid version even exists).

Please add any further information to #3.

Some useful information would be the raw post_meta values for that specific post as well as the raw `post_content` taken from the database.

**Closed as completed by rchipka** 2018-10-09 16:14 UTC

**Comment by signaturesteve** [comment] 2018-10-09 16:23
It means the fields become basically unusable
